services:
    excdev-nginx:
        container_name: excdev-nginx
        build: ./docker/nginx
        volumes:
            - .:/var/www/html
        ports:
            - 80:80

    excdev-php:
        container_name: excdev-php
        build: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

    excdev-mysql:
        container_name: excdev-mysql
        build: docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: excdev_db
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - 3306:3306
